<?php

namespace CarteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CircuitnotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircuitnotationRepository extends EntityRepository
{
}
