<?php

namespace CarteBundle\Repository;

use Doctrine\DBAL\Query\QueryBuilder;
use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    public function searchloca($category = "ALL"){
        $qb = $this->createQueryBuilder('l');
        $qb->select('l');
        if($category != "ALL"){
            $qb->where('l.type = :category');
            $qb->setParameter('category', $category);
        }

        return $qb->getQuery()->getResult();
    }
}