<?php

namespace CarteBundle\Repository;

use Doctrine\DBAL\Query\QueryBuilder;
use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    public function searchloca($category){
        $qb = $this->createQueryBuilder('l')
            ->select('l')
            ->where('l.type = :category')
            ->setParameter('category', $category)
            ->getQuery();

        return $qb->getResult();
    }
}
