index:
    path:     /index
    defaults: { _controller: CarteBundle:Main:index }

ranking:
    path:     /ranking
    defaults: { _controller: CarteBundle:Main:ranking }

tourchoice:
    path:     /tourchoice
    defaults: { _controller: CarteBundle:Main:tourchoice }

generator:
    path:     /generator/{data}
    defaults: { _controller: CarteBundle:Main:generator }

