index:
    path:     /index
    defaults: { _controller: CarteBundle:Main:index }

ranking:
    path:     /ranking
    defaults: { _controller: CarteBundle:Main:ranking }

tourchoice:
    path:     /tourchoice
    defaults: { _controller: CarteBundle:Main:tourchoice }

generator:
    path:     /generator
    defaults: { _controller: CarteBundle:Main:generator }
    methods:  [GET, POST]

circuit_display:
    path:     /circuitchosen/{idc}
    defaults: { _controller: CarteBundle:Main:circuitDisplay }
    methods:  [GET, POST]

generatorform:
    path:     /formgenerate
    defaults: { _controller: CarteBundle:Main:newGenerator }
    methods:  [GET, POST]
