fradou_user:
    resource: "@fradouUserBundle/Resources/config/routing.yml"
    prefix:   /

carte:
    resource: "@CarteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
