# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.OpenLyon_getter:
        class:  MigrationBundle\Service\PlaceApiGetter

    app.OpenLyon_logger:
        class:  MigrationBundle\Service\GetDataLogs
        arguments: ['@Logger']
        tags:
          - { name: monolog.logger, channel: opendata }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
