fradou\UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: fradou\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '50'
            unique: true
        firstName:
            type: string
            length: '50'
            nullable: true
        lastName:
            type: string
            length: '50'
            nullable: true
        language:
            type: string
            length: '2'
            nullable: true
    manyToMany:
        circuits:
            targetEntity: CarteBundle\Entity\Circuit
            inversedBy: users
            joinTable:
                name: users_circuits
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    circuit_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
