carte_circuit:
    resource: "@CarteBundle/Resources/config/routing/circuit.yml"
    prefix:   /circuit

carte_notation:
    resource: "@CarteBundle/Resources/config/routing/notation.yml"
    prefix:   /notation

carte_main:
    resource: "@CarteBundle/Resources/config/routing/main.yml"
    prefix:   /

carte_location:
    resource: "@CarteBundle/Resources/config/routing/location.yml"
    prefix:   /location

