CarteBundle\Entity\Circuitnotation:
    type: entity
    table: null
    repositoryClass: CarteBundle\Repository\CircuitnotationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        rating:
            type: integer
            nullable: true
        comment:
            type: text
            nullable: true
        status:
            type: string
            length: 255
        experience:
            type: integer
            nullable: true
    manyToOne:
        circuit:
            targetEntity: CarteBundle\Entity\Circuit
            inversedBy: circuitnotations
            joinColumn:
                name: circuit_id
                referencedColumnName: id
        user:
            targetEntity: fradou\UserBundle\Entity\User
            inversedBy: circuitnotations
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
