CarteBundle\Entity\Circuit:
    type: entity
    table: null
    repositoryClass: CarteBundle\Repository\CircuitRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
            unique: true
        category:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        cost:
            type: float
            nullable: true
    oneToMany:
        circuitnotations:
            targetEntity: CarteBundle\Entity\Circuitnotation
            mappedBy: circuit
        positions:
            targetEntity: CarteBundle\Entity\Position
            cascade: [persist]
            mappedBy: circuit
    lifecycleCallbacks: {  }
