CarteBundle\Entity\Notation:
    type: entity
    table: null
    repositoryClass: CarteBundle\Repository\NotationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        rating:
            type: integer
            nullable: true
        comment:
            type: text
            nullable: true
    manyToOne:
        location:
            targetEntity: CarteBundle\Entity\Location
            inversedBy: notations
            joinColumn:
                name: location_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
