CarteBundle\Entity\Position:
    type: entity
    table: null
    repositoryClass: CarteBundle\Repository\PositionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pos:
            type: integer
    manyToOne:
        location:
            targetEntity: CarteBundle\Entity\Location
            inversedBy: positions
            joinColumn:
                name: location_id
                referencedColumnName: id
        circuit:
            targetEntity: CarteBundle\Entity\Circuit
            inversedBy: positions
            joinColumn:
                name: circuit_id
                referencedColumnName: id
    oneToMany:
        users:
            targetEntity: CarteBundle\Entity\User
            mappedBy: position

    lifecycleCallbacks: {  }
