CarteBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: CarteBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            unique: true
    oneToMany:
        circuitnotations:
            targetEntity: CarteBundle\Entity\Circuitnotation
            mappedBy: user
    manyToOne:
        position:
          targetEntity: CarteBundle\Entity\Position
          inversedBy: users
          joinColumn:
            name: position_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
